### ISSUE TITLE
Better name would have been ....

### ISSUE THREAD

**Issue by kentfredric** [RsrchBoy/task-travisci-cache#1]
`Task::BeLike::RSRCHBOY::TravisCache`

Mostly, because the documentation and dependencies are clear signifiers that it is an author-specific utility, not a utility intended for general consumption (albeit capable of it, in the same way people use AVARs dzil bundle )

**Comment by rsrchboy** [comment]
Thanks!  Right now it is fairly me-specific, as that's an easy initial target, but I am aiming for a more general utility.  Perhaps it would have been less arrogant of me to have chosen a more specific namespace, then moved over as things progressed.
